const AboutPage = () => {
  return (
    <div className="About">
      <h1>About page</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque vehicula turpis quis massa euismod ultricies. Aliquam accumsan quam justo, quis varius orci ultrices vitae. Pellentesque ac ligula eros. Praesent vitae mi tempor, facilisis mauris et, eleifend mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce maximus mi id iaculis tristique. Cras et arcu sit amet leo posuere scelerisque eget nec diam.

      Morbi risus leo, porttitor ac ante in, luctus porta nunc. Suspendisse potenti. Maecenas in arcu sed purus hendrerit mattis id et nunc. Proin fermentum varius faucibus. Proin sed ex sed mi pharetra tincidunt quis a urna. Ut ullamcorper lorem aliquet, porttitor purus a, aliquet neque. Praesent sed nunc quis libero viverra pretium sit amet non quam. Cras aliquet augue turpis, quis molestie mi blandit eget. Quisque quis velit ac tellus molestie fringilla. Fusce sapien purus, vulputate sed enim vitae, mattis imperdiet elit. Praesent in viverra augue. Vivamus vitae dui sed quam commodo consequat non ac elit. Ut urna arcu, consectetur ac mauris id, egestas efficitur velit. Nunc dolor elit, blandit id gravida quis, dictum a eros. Fusce dignissim enim eu gravida vestibulum. Donec mollis massa a lectus viverra, a facilisis ligula bibendum.

      Vivamus gravida ligula et eros eleifend aliquet. Mauris odio nisi, fermentum non maximus eu, rutrum sit amet leo. Suspendisse et dictum risus. Duis bibendum dapibus velit, vehicula sagittis nisl malesuada sed. Morbi molestie lacus feugiat nibh hendrerit lacinia. In at leo vel tellus porta sodales non eget massa. Pellentesque sodales arcu mollis efficitur pellentesque.

      Vestibulum sed metus at elit scelerisque iaculis quis id dui. Nulla molestie auctor ultrices. Nulla diam velit, condimentum eu sollicitudin ac, dictum quis magna. Sed nec venenatis nulla. In gravida consectetur convallis. Curabitur pharetra orci vel aliquam vehicula. Phasellus et ex vel dolor malesuada ultrices. Nullam luctus, mauris non bibendum auctor, eros libero finibus lorem, nec convallis leo neque ut velit.

      Duis ultrices dapibus ipsum, sed ultrices sapien. Aliquam erat volutpat. Proin eu iaculis mauris, eu imperdiet mi. Vestibulum a lacus id sem dignissim bibendum ac rhoncus metus. Aliquam sodales augue et ipsum venenatis auctor. Donec id viverra est. Aenean nulla metus, dictum vitae bibendum ornare, finibus non turpis. Nunc eget orci at quam ultrices rhoncus nec nec risus.

      Pellentesque in justo quis eros lobortis rhoncus. Sed ac vestibulum diam, at tincidunt erat. Phasellus at vehicula ligula. In gravida gravida magna, a faucibus nisi porttitor in. Praesent sed odio ut lectus auctor volutpat quis vitae odio. Curabitur egestas efficitur risus mollis eleifend. Vivamus interdum turpis vitae massa malesuada lobortis. Donec at massa non ex ullamcorper ullamcorper ut aliquam neque.

      Sed eget justo non ipsum tristique auctor non sed nisi. Praesent mollis ornare suscipit. Sed accumsan orci vitae diam laoreet eleifend. Donec dapibus ex nec eros consectetur pulvinar. Maecenas dapibus sed massa in sagittis. Vivamus tempus risus nisl, ac fringilla diam finibus vel. Morbi aliquet lacus ut elit dapibus, eu malesuada tortor convallis. Mauris venenatis eros ac interdum tempus. Duis iaculis felis quis dictum gravida. Curabitur ac augue hendrerit velit posuere molestie. Aenean fringilla posuere tellus, non hendrerit quam gravida quis. Proin condimentum accumsan volutpat. In hac habitasse platea dictumst.

      Aenean semper leo ut enim varius ornare. Nullam vitae lorem id odio vulputate rhoncus in non nisl. Aenean blandit ipsum libero. Vestibulum lobortis nec velit eu fringilla. In ac dui quis lectus laoreet tristique. Duis fringilla arcu risus, ac dignissim nunc varius eu. Duis a velit vehicula, venenatis ipsum nec, dignissim leo. Integer massa ante, tristique consequat ornare nec, fermentum ut risus. Maecenas gravida eros urna, vitae ultricies augue ultrices ac. Sed gravida sagittis condimentum. Proin at ipsum nulla.

      In hendrerit efficitur quam sed rhoncus. Sed erat nibh, vulputate id sapien a, vulputate sodales augue. Suspendisse suscipit facilisis eros ut aliquet. Sed eget justo massa. Aliquam nec venenatis nisi, vel blandit ante. Nullam ac malesuada neque, id ultrices purus. Nulla et hendrerit lacus, quis malesuada ex.

      Maecenas blandit commodo ipsum, nec cursus neque finibus id. Donec sit amet turpis odio. Proin dapibus a eros vitae feugiat. Vivamus id orci et arcu viverra sollicitudin nec imperdiet orci. Nullam in dui nisl. Aenean ullamcorper, neque porta bibendum suscipit, mi dolor pharetra metus, quis ultricies velit orci sit amet ligula. Integer pharetra hendrerit urna in tristique. Cras varius eget ipsum imperdiet porttitor.

      Maecenas turpis velit, viverra sed vehicula ac, ornare vel lacus. Vestibulum ex arcu, vestibulum et nibh ornare, sollicitudin volutpat ante. Vestibulum rutrum, velit id mollis molestie, arcu metus blandit leo, ac convallis libero sem id ex. Nullam non nunc enim. Vestibulum at arcu nec sem convallis tempus. Cras rutrum eu quam in sagittis. Integer sed magna mi.

      Vivamus eu venenatis augue. Mauris consequat purus quis auctor ornare. Curabitur ac neque vel neque aliquam tincidunt. Suspendisse interdum, quam vitae tincidunt mollis, diam velit efficitur nisi, eu sodales diam lacus et tortor. Sed pharetra sagittis tempor. Nunc viverra varius suscipit. Quisque et commodo nulla. Morbi tempor, dolor eu vulputate lacinia, ipsum erat volutpat purus, at convallis lectus tellus in leo. Ut a neque nisi. Quisque posuere neque nec condimentum dapibus. Mauris lobortis mattis sapien nec viverra. Donec massa metus, iaculis in cursus nec, molestie imperdiet ligula. Sed vulputate magna dapibus lacus sollicitudin tincidunt. In eu leo consectetur, tincidunt nisi a, rhoncus libero.

      Cras pulvinar nibh ipsum, at sodales ligula interdum nec. Praesent ut purus aliquet, viverra tortor id, iaculis odio. Nam vulputate convallis rutrum. Praesent eros urna, sodales vel libero eget, dictum posuere purus. Quisque sed fringilla neque. Ut dapibus nec magna sed pulvinar. Pellentesque sit amet lorem blandit, mollis nunc vel, placerat elit. Nunc in condimentum ipsum. Etiam sit amet lectus dui.

      Vivamus imperdiet vestibulum eros, eget ornare velit tristique vitae. Vestibulum ac tortor placerat, placerat quam et, euismod libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed pharetra nibh nec tellus porta vestibulum. Duis in eleifend massa, id semper urna. Aenean in diam pharetra, ultricies turpis id, gravida justo. Vivamus placerat euismod rhoncus. Duis a lectus quis dui aliquam auctor. Maecenas id mauris nec nulla aliquet malesuada. Morbi ornare eros et tortor iaculis, a fermentum nisi eleifend. Vivamus nec enim quis elit fermentum scelerisque. Morbi sollicitudin magna feugiat, dictum libero quis, sollicitudin sem. Duis dignissim laoreet dolor id scelerisque. Nam eu eros nisl. Aenean tempor lacus lectus, ut pellentesque purus convallis vitae.

      Vivamus et risus maximus, placerat mi vel, eleifend magna. Nunc ac mi et diam bibendum porttitor sed ut nunc. Ut tristique elit ac elit congue consectetur. Phasellus arcu sapien, ornare eu elit eu, aliquet ullamcorper nulla. Suspendisse potenti. Donec ultrices enim sed risus maximus, eget porta eros mollis. Donec feugiat, augue ac auctor porttitor, neque sem mollis velit, nec cursus odio tortor sit amet sapien. Nulla facilisi. Nunc augue enim, consectetur id ante at, iaculis mollis mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas augue magna, ornare ac porttitor a, sodales eget tortor. Donec vestibulum pulvinar quam ut faucibus. Morbi sit amet urna nunc. Integer tincidunt, libero in dignissim lobortis, tortor arcu ultrices justo, ac porta turpis metus non nibh.

      Quisque egestas, massa a rhoncus rhoncus, odio est venenatis dui, eget sollicitudin leo nisi sed justo. In et odio varius, mattis est ac, laoreet libero. Nullam viverra sem vel orci tristique bibendum. Etiam porta nec libero eu gravida. Pellentesque eu quam eu massa commodo tincidunt. Vivamus sollicitudin sapien quis mauris mollis sagittis. Nunc faucibus nisi a velit vehicula tincidunt eget ut sem. Praesent sit amet ipsum lobortis urna sollicitudin porttitor in pretium lacus. Quisque nec erat vitae tellus tincidunt ultrices. Integer mollis nisi sit amet dolor consequat, a tincidunt ex fringilla. Donec id est risus. Cras consequat urna quis consequat tristique.

      Quisque consequat molestie turpis eget dictum. Pellentesque consequat ante id libero sodales, a malesuada ante eleifend. Suspendisse potenti. Nunc in metus orci. Nunc a libero convallis, laoreet ex ut, suscipit augue. Donec convallis suscipit erat sit amet condimentum. Mauris nisi erat, egestas quis quam in, interdum efficitur neque. Phasellus vel erat pharetra, iaculis justo a, dapibus neque. Sed a euismod ligula, a accumsan elit.

      Donec mollis porttitor nibh, et hendrerit lorem finibus nec. Vivamus euismod id tellus a volutpat. Cras facilisis sapien at mattis consequat. Sed sodales ultrices felis, eu eleifend neque feugiat sed. Duis ac aliquet justo. Vivamus in lorem in turpis scelerisque iaculis. Sed pulvinar elit eget leo bibendum tempor. Pellentesque quis nunc quis tellus fermentum ornare. Integer at fermentum augue.

      Etiam maximus augue mollis tellus accumsan, et auctor libero sagittis. Suspendisse gravida gravida metus at porttitor. Nunc convallis velit quis ante ultrices, a accumsan diam scelerisque. Aliquam odio massa, ultricies nec orci non, tempor aliquet nisi. Donec varius, tellus sed sodales molestie, orci risus faucibus diam, non vulputate augue enim ac velit. Suspendisse tristique leo sed odio molestie fermentum. Aliquam in ligula eros. Pellentesque pretium arcu velit, mollis hendrerit risus auctor et. Phasellus placerat fermentum feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

      Aenean aliquam rhoncus nibh, nec hendrerit ligula ultrices sit amet. Mauris ut libero a felis dapibus convallis. Maecenas et augue pretium, malesuada felis et, aliquam nunc. Vivamus fringilla, ligula in accumsan cursus, neque turpis volutpat enim, non ornare ligula eros sollicitudin nisi. Nulla quis elit sit amet enim egestas lacinia. Fusce pretium metus felis, sit amet consequat ex congue eget. Donec urna lorem, tristique vel augue a, fringilla dictum lectus. Nulla at ante sit amet dui euismod porttitor. Proin a aliquet leo. Proin arcu urna, condimentum sit amet venenatis eu, dictum ac diam. Nunc ultricies, ipsum eu ullamcorper faucibus, ipsum libero tempus lectus, consectetur accumsan nibh magna et enim. Morbi vel ullamcorper dolor. Etiam feugiat orci non ex cursus, vel vulputate arcu semper. Vivamus quis suscipit urna. Nullam lacinia nec arcu ac eleifend. Pellentesque egestas massa purus.</p>
    </div>
  )
}

export default AboutPage